# Site settings
email: pr@csh.rit.edu
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Computer Science House
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Computer Science House
profile_img: 
profile: 
social:
  github: https://github.com/ComputerScienceHouse

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
